# [START functions_ci_cd_cloud_build]
steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'functions/dir/from/repo/root'
#  - name: 'gcr.io/cloud-builders/npm'
#    args: ['test']
#    dir: 'function/dir/from/repo/root'
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args:
#      - functions
#      - deploy
#      - startPoint
#      - --entry-point=get
#      - --runtime=nodejs12
#      - --source=.
#      - --trigger-http
  - name: gcr.io/cs3219taskb3/firebase
    args: ['deploy']
# [END functions_ci_cd_cloud_build]
