# [START functions_ci_cd_cloud_build]
steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'function/dir/from/repo/root'
#  - name: 'gcr.io/cloud-builders/npm'
#    args: ['test']
#    dir: 'function/dir/from/repo/root'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - startPoint
      - --runtime=nodejs12
      - --source=.
      - --trigger-http
# [END functions_ci_cd_cloud_build]
